const TASK_STATUS = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE'
};

const TASK_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

const TRIGGER_TYPE = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_PRIORITY_CHANGED: 'TASK_PRIORITY_CHANGED',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  TASK_OVERDUE: 'TASK_OVERDUE',
  SUBTASK_COMPLETED: 'SUBTASK_COMPLETED'
};

const CONDITION_OPERATOR = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  CONTAINS: 'CONTAINS',
  IN: 'IN',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  WITHIN_NEXT_HOURS: 'WITHIN_NEXT_HOURS',
  IS_EMPTY: 'IS_EMPTY',
  IS_NOT_EMPTY: 'IS_NOT_EMPTY'
};

const ACTION_TYPE = {
  CHANGE_PRIORITY: 'CHANGE_PRIORITY',
  CHANGE_STATUS: 'CHANGE_STATUS',
  ADD_TAG: 'ADD_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
  CREATE_REMINDER: 'CREATE_REMINDER',
  CREATE_FOLLOW_UP_TASK: 'CREATE_FOLLOW_UP_TASK',
  ADD_SUBTASK: 'ADD_SUBTASK'
};

const NOTIFICATION_TYPE = {
  TASK_DUE: 'TASK_DUE',
  TASK_OVERDUE: 'TASK_OVERDUE',
  AUTOMATION_ACTION: 'AUTOMATION_ACTION',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

const NOTIFICATION_PRIORITY = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  URGENT: 'URGENT'
};

const EXECUTION_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
};

module.exports = {
  TASK_STATUS,
  TASK_PRIORITY,
  TRIGGER_TYPE,
  CONDITION_OPERATOR,
  ACTION_TYPE,
  NOTIFICATION_TYPE,
  NOTIFICATION_PRIORITY,
  EXECUTION_STATUS
};
